Fix DNS config, expired certificates, and missing requirements
fkie-cad/socbed pull request #94
Opened 2024-10-28 07:18 UTC by Maspital

This addresses a couple of small issues:
- The attacker did not have internet access post-provisioning due to missing DNS config
  - I opted to simply set it directly via `/etc/resolv.conf`, aka, without systemd-resolved
- The attacker couldn't access package repositories due to expired certificates
  - Fixed by adding the current keychain during the post-boot command
- The external mail handler running on the attacker is missing the aiosmtpd package
  - This change is recent, I simply forgot to also add this packet when updating from the deprecated smtpd
- Sometimes, the Internet Router is unable to provide internet access to the rest of the network (and itself) for a short period of time
  - Bumping to the latest 2.x core version does not solve this
  - Seems to work reliably when explicitly setting DNS in `/var/ipfire/dns/servers` (I chose quad8)
  - On the same note, while upgrading from core141 to 157 on the internet router works without problems, it messes up the provisioning on the company router by preventing ansible from reconnecting after a restart (see [here](https://forum.ansible.com/t/reboot-task-no-longer-reconnects-or-times-out/10483)). We could still upgrade by running `pakfire update`/`pakfire upgrade` as the last provisioning step, but this takes quite a while, so I've opted to leave it at 141.

Resolves #93 
Resolves #92 
Also related to the mail handler issue mentioned in #80

2024-10-30 18:41 UTC, ru37z requested changes
Discussion required

2024-10-30 18:41 UTC, ru37z commented on provisioning/ansible/roles/external_mail_handler/tasks/main.yml
> +- name: Upgrade binutils
A principal idea of SOCBED is to pin as many package versions as possible to (1) ensure reproducibility and (2) avoid unforeseen problems in the future. I'm actually not sure how many packages and other software are currently affected by this, we should discuss whether is makes sense to pin for example this package version here.

2024-10-31 15:04 UTC, ru37z approved these changes

2024-10-31 15:04 UTC, merged

2024-12-10 08:03 UTC, 1ncludeSteven commented
If you want to upgrade company router from IPFire2.25 to IPFire2.29, then current packetbeat version can not be executed correctly with error message `runtime/cgo: pthread_create failed: Operation not permitted
`

2024-12-10 08:27 UTC, Maspital commented
> If you want to upgrade company router from IPFire2.25 to IPFire2.29, then current packetbeat version can not be executed correctly with error message `runtime/cgo: pthread_create failed: Operation not permitted `

We've decided to not upgrade the company router for now since the current older version works fine. But thank you for the heads-up!